import { useEffect, useState, type FormEvent } from 'react'
import type { AlbumCreate, AlbumRead, AlbumTrackWrite, MediaFormat } from '../../../api/apiTypes'
import { useArtists, useCreateArtist } from '../../../api/artistsQueries'
import { useGenres, useCreateGenre } from '../../../api/genresQueries'
import { useShelves } from '../../../api/shelvesQueries'
import { useAlbumLookup } from '../../../api/albumsQueries'
import { Alert, Button, Field, LoadingState, QueryErrorState } from '../../../components'
import { formatArtist } from '../albumDisplay'

const FORMATS: MediaFormat[] = ['vinyl', 'cd', 'cassette', 'other', 'unknown']
const slugify = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
export function AlbumForm({ album, onSubmit, onCancel, submitting = false }: { album?: AlbumRead; onSubmit: (value: AlbumCreate) => Promise<void>; onCancel: () => void; submitting?: boolean }) {
    const artists = useArtists(); const genres = useGenres(); const shelves = useShelves(); const createArtist = useCreateArtist(); const createGenre = useCreateGenre()
    const [title, setTitle] = useState(album?.title ?? ''); const [artistIds, setArtistIds] = useState(album?.artists.map(x => x.artist_id) ?? []); const [genreIds, setGenreIds] = useState(album?.genres.map(x => x.genre_id) ?? []); const [format, setFormat] = useState<MediaFormat>(album?.media_format ?? 'unknown'); const [shelf, setShelf] = useState(album?.shelf_name ?? ''); const [barcode, setBarcode] = useState(album?.barcode ?? ''); const [label, setLabel] = useState(album?.label ?? ''); const [releaseDate, setReleaseDate] = useState(album?.release_date ?? ''); const [notes, setNotes] = useState(album?.notes ?? ''); const [tracks, setTracks] = useState(album?.tracks.map(x => x.title).join('\n') ?? ''); const [lookupValue, setLookupValue] = useState(''); const [lookupKind, setLookupKind] = useState<'barcode' | 'discogs'>('barcode'); const [lookupEnabled, setLookupEnabled] = useState(false); const [error, setError] = useState<string | null>(null)
    const lookup = useAlbumLookup(lookupValue, lookupKind, lookupEnabled)
    // A completed external lookup intentionally hydrates the editable local draft.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => { const draft = lookup.data?.draft; if (!lookup.data || !draft) return; setTitle(draft.title); setBarcode(draft.barcode ?? ''); setLabel(draft.label ?? ''); setReleaseDate(draft.release_date ?? ''); setFormat(draft.media_format); setTracks((draft.tracks ?? []).map(x => x.title).join('\n')); setLookupEnabled(false) }, [lookup.data])
    if (artists.isPending || genres.isPending || shelves.isPending) return <LoadingState label="Loading album form…" />
    if (artists.isError || genres.isError || shelves.isError) return <QueryErrorState title="Unable to load album form" error={artists.error ?? genres.error ?? shelves.error} />
    const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); if (!title.trim()) { setError('Title is required.'); return } if (!artistIds.length) { setError('Select at least one artist.'); return } try { const parsedTracks: AlbumTrackWrite[] = tracks.split('\n').map(x => x.trim()).filter(Boolean).map((trackTitle, index) => ({ title: trackTitle, disc_number: 1, track_number: index + 1 })); await onSubmit({ title: title.trim(), artist_ids: artistIds, genre_ids: genreIds, media_format: format, shelf_name: shelf || undefined, barcode: barcode.trim() || null, label: label.trim() || null, release_date: releaseDate || null, notes: notes.trim() || null, tracks: parsedTracks, is_played: album?.is_played ?? false, status: album?.status ?? 'available', completion_date: album?.completion_date ?? null, rating: album?.rating ?? null, review: album?.review ?? null, discogs_release_id: album?.discogs_release_id ?? (lookupKind === 'discogs' && lookup.data?.found ? lookupValue : null), musicbrainz_release_id: lookup.data?.draft?.musicbrainz_release_id ?? album?.musicbrainz_release_id ?? null }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save album.') } }
    const addArtist = async () => { const name = prompt('Artist name (first name and surname)')?.trim(); if (!name) return; const parts = name.split(/\s+/); const created = await createArtist.mutateAsync({ surname: parts.pop()!, first_name: parts.join(' ') || null }); setArtistIds(x => [...x, created.artist_id]) }
    const addGenre = async () => { const name = prompt('Genre name')?.trim(); if (!name) return; const created = await createGenre.mutateAsync({ name, slug: slugify(name) }); setGenreIds(x => [...x, created.genre_id]) }
    return <form className="album-form" onSubmit={submit}>
        {error ? <Alert variant="error">{error}</Alert> : null}
        <section className="album-form__lookup"><h2>Metadata lookup</h2><p>Find a release, review the draft, then save explicitly.</p><div className="album-form__lookup-row"><select aria-label="Lookup type" value={lookupKind} onChange={e => setLookupKind(e.target.value as 'barcode' | 'discogs')}><option value="barcode">Barcode</option><option value="discogs">Discogs release ID</option></select><input aria-label="Lookup value" value={lookupValue} onChange={e => setLookupValue(e.target.value)} /><Button type="button" variant="secondary" disabled={!lookupValue.trim() || lookup.isFetching} onClick={() => setLookupEnabled(true)}>{lookup.isFetching ? 'Looking up…' : 'Look up'}</Button></div>{lookup.data && !lookup.data.found ? <Alert variant="info">No matching release was found. You can still enter it manually.</Alert> : null}</section>
        <section><h2>Release</h2><Field label="Title"><input value={title} onChange={e => setTitle(e.target.value)} required /></Field><Field label="Artists"><div><div className="album-form__choices">{artists.data.items.map(a => <label key={a.artist_id}><input type="checkbox" checked={artistIds.includes(a.artist_id)} onChange={e => setArtistIds(ids => e.target.checked ? [...ids, a.artist_id] : ids.filter(id => id !== a.artist_id))} /> {formatArtist(a)}</label>)}</div><Button type="button" variant="secondary" onClick={() => void addArtist()}>Add artist</Button></div></Field><Field label="Genres"><div><div className="album-form__choices">{genres.data.map(g => <label key={g.genre_id}><input type="checkbox" checked={genreIds.includes(g.genre_id)} onChange={e => setGenreIds(ids => e.target.checked ? [...ids, g.genre_id] : ids.filter(id => id !== g.genre_id))} /> {g.name}</label>)}</div><Button type="button" variant="secondary" onClick={() => void addGenre()}>Add genre</Button></div></Field><Field label="Format"><select value={format} onChange={e => setFormat(e.target.value as MediaFormat)}>{FORMATS.map(x => <option key={x} value={x}>{x}</option>)}</select></Field><Field label="Shelf"><select value={shelf} onChange={e => setShelf(e.target.value)}><option value="">No shelf (wishlist only)</option>{shelves.data.filter(x => x.common_name !== 'removed').map(x => <option key={x.shelf_id} value={x.common_name}>{x.common_name}</option>)}</select></Field><Field label="Barcode"><input value={barcode} onChange={e => setBarcode(e.target.value)} /></Field><Field label="Label"><input value={label} onChange={e => setLabel(e.target.value)} /></Field><Field label="Release date"><input type="date" value={releaseDate} onChange={e => setReleaseDate(e.target.value)} /></Field></section>
        <section><h2>Track list</h2><Field label="Tracks" helpText="One track title per line, in play order"><textarea rows={8} value={tracks} onChange={e => setTracks(e.target.value)} /></Field><Field label="Notes"><textarea rows={5} value={notes} onChange={e => setNotes(e.target.value)} /></Field></section>
        <div className="album-form__actions"><Button type="submit" disabled={submitting}>{submitting ? 'Saving…' : 'Save album'}</Button><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button></div>
    </form>
}
