import { useEffect, useState, type FormEvent } from 'react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { useAlbum, useCheckinAlbum, useCheckoutAlbum, useDeleteAlbum, useMarkAlbumPlayed, useRefetchAlbumArtwork, useRemoveAlbumArtwork, useRestoreAlbum, useUploadAlbumArtwork } from '../../../api/albumsQueries'
import { useLoans } from '../../../api/loansQueries'
import { Alert, AppLink, Button, Field, LoadingState, QueryErrorState } from '../../../components'
import { AlbumArtwork } from '../components/AlbumArtwork'
import { displayMediaFormat, formatAlbumArtists } from '../albumDisplay'
import { AddAlbumToWishlistControl } from '../../wishlists/components/AddAlbumToWishlistControl'
import { AddAlbumToCollectionControl } from '../../collections/components/AddAlbumToCollectionControl'
import { BorrowerReviews } from '../../loans/components/BorrowerReviews'
export function AlbumDetailsPage() {
 const id = useParams().albumId ?? ''; const navigate = useNavigate(); const location = useLocation(); const query = useAlbum(id); const loans = useLoans({ albumId: id, mediaType: 'album', enabled: Boolean(id) }); const checkout = useCheckoutAlbum(); const checkin = useCheckinAlbum(); const played = useMarkAlbumPlayed(); const del = useDeleteAlbum(); const restore = useRestoreAlbum(); const upload = useUploadAlbumArtwork(); const removeArtwork = useRemoveAlbumArtwork(); const refetch = useRefetchAlbumArtwork(); const [borrower, setBorrower] = useState(''); const [message, setMessage] = useState<string | null>(null)
 // Reset transient action feedback when navigating between album IDs.
    const [checkinRating, setCheckinRating] = useState('')
    const [checkinReview, setCheckinReview] = useState('')
    // eslint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => setMessage(null), [id]); if (query.isPending) return <LoadingState label="Loading album…" />; if (query.isError) return <QueryErrorState title="Unable to load album" error={query.error} onRetry={() => void query.refetch()} />; const album = query.data; const activeLoan = loans.data?.items.find(x => x.album_id === id && x.returned_at === null)
 const doCheckout = async (e: FormEvent) => { e.preventDefault(); if (!borrower.trim()) return; try { await checkout.mutateAsync({ id, request: { borrower: borrower.trim() } }); setBorrower(''); setMessage('Album checked out.') } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Checkout failed.') } }
 const albumsReturnTo = typeof location.state === 'object' && location.state !== null && 'albumsReturnTo' in location.state && typeof location.state.albumsReturnTo === 'string' && location.state.albumsReturnTo.startsWith('/albums') ? location.state.albumsReturnTo : '/albums'
 return <section className="page page--album-detail"><AppLink to={albumsReturnTo}>← Back to albums</AppLink><header className="album-detail__hero"><AlbumArtwork albumId={id} title={album.title} present={album.artwork_present} /><div><p className="page-eyebrow">Now selected</p><h1>{album.title}</h1><p className="album-detail__artist">{formatAlbumArtists(album)}</p><p>{[album.label, album.release_date?.slice(0,4), displayMediaFormat(album.media_format)].filter(Boolean).join(' · ')}</p><div className="album-detail__actions"><AppLink className="button button--secondary" to={`/albums/${id}/edit`}>Edit metadata</AppLink>{album.deletion_date ? <Button onClick={() => void restore.mutateAsync(id)}>Restore album</Button> : <Button variant="danger" onClick={() => { if (confirm('Soft-delete this album?')) void del.mutateAsync(id).then(() => navigate(albumsReturnTo)) }}>Delete album</Button>}</div></div></header>
 {message ? <Alert variant={message.endsWith('.') ? 'success' : 'error'}>{message}</Alert> : null}
<div className="album-detail__columns"><section className="album-liner-notes"><h2>Liner notes</h2><dl className="detail-list"><div><dt>Genres</dt><dd>{album.genres.map(x => x.name).join(', ') || 'Not recorded'}</dd></div><div><dt>Barcode</dt><dd>{album.barcode ?? 'Not recorded'}</dd></div><div><dt>Crate</dt><dd>{album.shelf_name}</dd></div><div><dt>Status</dt><dd>{album.status.replace('_', ' ')}</dd></div><div><dt>Owner listening rating</dt><dd>{album.is_played ? `Played${album.rating ? ` · ${album.rating}/5` : ''}` : 'Not played'}</dd></div><div><dt>Borrower rating</dt><dd>{album.borrower_rating?.count ? `${album.borrower_rating.average ?? 'Not recorded'} / 5 (${album.borrower_rating.count})` : 'No borrower ratings'}</dd></div></dl>{album.notes ? <p>{album.notes}</p> : null}{!album.is_played && !album.deletion_date ? <Button onClick={() => void played.mutateAsync({ id, request: {} }).then(() => setMessage('Album marked played.'))}>Mark played</Button> : null}</section>
 <section><h2>Track list</h2>{album.tracks.length ? <ol className="track-list">{album.tracks.map(track => <li key={track.album_track_id}><span>{track.disc_number}.{track.track_number}</span> {track.title}{track.duration ? <small>{track.duration}</small> : null}</li>)}</ol> : <p>No tracks recorded.</p>}</section></div>
{!album.deletion_date ? <section className="album-counter"><h2>Circulation counter</h2>{activeLoan ? <form onSubmit={(event) => { event.preventDefault(); const rating = Number(checkinRating); if (!Number.isInteger(rating) || rating < 1 || rating > 5) return; void checkin.mutateAsync({ id, request: { rating }, ...(checkinReview.trim() ? { feedback: { loanId: activeLoan.id, rating, review: checkinReview.trim() } } : {}) }).then(() => { setCheckinRating(''); setCheckinReview(''); setMessage('Album checked in.') }).catch((cause: unknown) => setMessage(cause instanceof Error ? cause.message : 'Check-in failed.')) }}><p>Checked out to <strong>{activeLoan.borrower}</strong>.</p><Field label="Borrower rating" helpText="Required; separate from the owner catalog rating."><select value={checkinRating} onChange={event => setCheckinRating(event.target.value)} required><option value="">Choose a rating</option>{[1, 2, 3, 4, 5].map(rating => <option key={rating} value={rating}>{rating} / 5</option>)}</select></Field><Field label="Borrower review" helpText="Optional. This is separate from the owner catalog review."><textarea value={checkinReview} onChange={event => setCheckinReview(event.target.value)} /></Field><Button type="submit" disabled={checkin.isPending || checkinRating === ''}>Check in</Button></form> : album.status === 'display_only' ? <Alert variant="info">This copy is display only.</Alert> : <form onSubmit={doCheckout}><Field label="Borrower"><input value={borrower} onChange={e => setBorrower(e.target.value)} required /></Field><Button type="submit" disabled={checkout.isPending}>Check out</Button></form>}</section> : null}
 <section className="album-artwork-manager"><h2>Artwork</h2><p>Artwork stays private and is always loaded through Shade.</p><input aria-label="Upload artwork" type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { const file=e.target.files?.[0]; if(file) void upload.mutateAsync({id,file}) }} />{album.artwork_present ? <Button variant="secondary" onClick={() => void removeArtwork.mutateAsync(id)}>Remove artwork</Button> : null}{album.musicbrainz_release_id ? <Button variant="secondary" onClick={() => void refetch.mutateAsync({ id, replaceOwnerUpload: false }).catch(() => setMessage('Artwork refetch needs confirmation or could not complete.'))}>Refetch artwork</Button> : null}</section>
 {album.shelf_name === 'unknown' && !album.deletion_date ? <section className="album-detail__wishlist"><h2>Wishlist</h2><p>Save this unshelved record to a wishlist.</p><AddAlbumToWishlistControl albumId={id} albumTitle={album.title} /></section> : null}
 {!album.deletion_date ? <section className="album-detail__collection"><h2>Collections</h2><p>Add this record to a curated collection without changing its crate or wishlist placement.</p><AddAlbumToCollectionControl albumId={id} albumTitle={album.title} /></section> : null}
 <BorrowerReviews albumId={id} loans={loans.data?.items ?? []} />
 <section><h2>Loan history</h2>{loans.isPending ? <LoadingState label="Loading album loans…" /> : loans.isError ? <QueryErrorState title="Unable to load album loans" error={loans.error} /> : loans.data.items.length ? <ul>{loans.data.items.map(loan => <li key={loan.id}>{loan.borrower} · {new Date(loan.checked_out_at).toLocaleDateString()} · {loan.returned_at ? 'Returned' : 'Active'}</li>)}</ul> : <p>No loans recorded.</p>}</section>
 </section>
}
