import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAlbum, useCheckinAlbum, useCheckoutAlbum, useDeleteAlbum, useMarkAlbumPlayed, useRefetchAlbumArtwork, useRemoveAlbumArtwork, useRestoreAlbum, useUploadAlbumArtwork } from '../../../api/albumsQueries'
import { useLoans } from '../../../api/loansQueries'
import { Alert, AppLink, Button, Field, LoadingState, QueryErrorState } from '../../../components'
import { AlbumArtwork } from '../components/AlbumArtwork'
import { displayMediaFormat, formatAlbumArtists } from '../albumDisplay'
export function AlbumDetailsPage() {
 const id = useParams().albumId ?? ''; const navigate = useNavigate(); const query = useAlbum(id); const loans = useLoans({ albumId: id, mediaType: 'album', enabled: Boolean(id) }); const checkout = useCheckoutAlbum(); const checkin = useCheckinAlbum(); const played = useMarkAlbumPlayed(); const del = useDeleteAlbum(); const restore = useRestoreAlbum(); const upload = useUploadAlbumArtwork(); const removeArtwork = useRemoveAlbumArtwork(); const refetch = useRefetchAlbumArtwork(); const [borrower, setBorrower] = useState(''); const [message, setMessage] = useState<string | null>(null)
 // Reset transient action feedback when navigating between album IDs.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(() => setMessage(null), [id]); if (query.isPending) return <LoadingState label="Loading album…" />; if (query.isError) return <QueryErrorState title="Unable to load album" error={query.error} onRetry={() => void query.refetch()} />; const album = query.data; const activeLoan = loans.data?.items.find(x => x.album_id === id && x.returned_at === null)
 const doCheckout = async (e: FormEvent) => { e.preventDefault(); if (!borrower.trim()) return; try { await checkout.mutateAsync({ id, request: { borrower: borrower.trim() } }); setBorrower(''); setMessage('Album checked out.') } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Checkout failed.') } }
 return <section className="page page--album-detail"><header className="album-detail__hero"><AlbumArtwork albumId={id} title={album.title} present={album.artwork_present} /><div><p className="page-eyebrow">Now selected</p><h1>{album.title}</h1><p className="album-detail__artist">{formatAlbumArtists(album)}</p><p>{[album.label, album.release_date?.slice(0,4), displayMediaFormat(album.media_format)].filter(Boolean).join(' · ')}</p><div className="album-detail__actions"><AppLink className="button button--secondary" to={`/albums/${id}/edit`}>Edit metadata</AppLink>{album.deletion_date ? <Button onClick={() => void restore.mutateAsync(id)}>Restore album</Button> : <Button variant="danger" onClick={() => { if (confirm('Soft-delete this album?')) void del.mutateAsync(id).then(() => navigate('/albums')) }}>Delete album</Button>}</div></div></header>
 {message ? <Alert variant={message.endsWith('.') ? 'success' : 'error'}>{message}</Alert> : null}
 <div className="album-detail__columns"><section><h2>Release notes</h2><dl className="detail-list"><div><dt>Genres</dt><dd>{album.genres.map(x => x.name).join(', ') || 'Not recorded'}</dd></div><div><dt>Barcode</dt><dd>{album.barcode ?? 'Not recorded'}</dd></div><div><dt>Shelf</dt><dd>{album.shelf_name}</dd></div><div><dt>Status</dt><dd>{album.status.replace('_', ' ')}</dd></div><div><dt>Listening</dt><dd>{album.is_played ? `Played${album.rating ? ` · ${album.rating}/5` : ''}` : 'Not played'}</dd></div></dl>{album.notes ? <p>{album.notes}</p> : null}{!album.is_played && !album.deletion_date ? <Button onClick={() => void played.mutateAsync({ id, request: {} }).then(() => setMessage('Album marked played.'))}>Mark played</Button> : null}</section>
 <section><h2>Track list</h2>{album.tracks.length ? <ol className="track-list">{album.tracks.map(track => <li key={track.album_track_id}><span>{track.disc_number}.{track.track_number}</span> {track.title}{track.duration ? <small>{track.duration}</small> : null}</li>)}</ol> : <p>No tracks recorded.</p>}</section></div>
 {!album.deletion_date ? <section className="album-counter"><h2>Circulation counter</h2>{activeLoan ? <><p>Checked out to <strong>{activeLoan.borrower}</strong>.</p><Button onClick={() => void checkin.mutateAsync({ id }).then(() => setMessage('Album checked in.'))}>Check in</Button></> : album.status === 'display_only' ? <Alert variant="info">This copy is display only.</Alert> : <form onSubmit={doCheckout}><Field label="Borrower"><input value={borrower} onChange={e => setBorrower(e.target.value)} required /></Field><Button type="submit" disabled={checkout.isPending}>Check out</Button></form>}</section> : null}
 <section className="album-artwork-manager"><h2>Artwork</h2><p>Artwork stays private and is always loaded through Shade.</p><input aria-label="Upload artwork" type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { const file=e.target.files?.[0]; if(file) void upload.mutateAsync({id,file}) }} />{album.artwork_present ? <Button variant="secondary" onClick={() => void removeArtwork.mutateAsync(id)}>Remove artwork</Button> : null}{album.musicbrainz_release_id ? <Button variant="secondary" onClick={() => void refetch.mutateAsync({ id, replaceOwnerUpload: false }).catch(() => setMessage('Artwork refetch needs confirmation or could not complete.'))}>Refetch artwork</Button> : null}</section>
 <section><h2>Loan history</h2>{loans.isPending ? <LoadingState label="Loading album loans…" /> : loans.isError ? <QueryErrorState title="Unable to load album loans" error={loans.error} /> : loans.data.items.length ? <ul>{loans.data.items.map(loan => <li key={loan.id}>{loan.borrower} · {new Date(loan.checked_out_at).toLocaleDateString()} · {loan.returned_at ? 'Returned' : 'Active'}</li>)}</ul> : <p>No loans recorded.</p>}</section>
 </section>
}
